### ISSUE TITLE
Not working with Vaadin 23.2

### ISSUE THREAD

**Issue by echarlus** [vaadin-component-factory/multiselect-combo-box#28]
Hi,
first of all thanks for this great contribution ! I was happy to see that you released a fix for it work with Vaadin 23.1.X and I happily used it ;)
Now I'm trying to upgrade to 23.2 and the component breaks again. I had a quick look at the changes made to fix the issue on Vaadin 23.1.x but I could not find an obvious enhancement to make it work on 23.2 ...
I'm getting the following error in the Vaadin console:

Uncaught TypeError: this._setOverlayItems is not a function (http://localhost:8080/VAADIN/@fs/PROJECT_PATH/node_modules/.vite/deps/@vaadin-component-factory_vcf-multiselect-combo-box_src_vcf-multiselect-combo-box__js.js?v=611e7736:147:8)

**Comment by McPringle** [comment]
Same with my application. Is someone working on this issue or is it just sitting around? Can I help with reports and tests?

**Comment by jcgueriaud1** [comment]
I didn't have the time to work on it or check if a lot of changes is needed. As a workaround you can use the official Vaadin multi select component.
